# Generated by Django 4.2.5 on 2023-10-04 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0001_initial'),
    ]

    operations = [
    ]
