# Generated by Django 4.2.5 on 2023-10-03 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('student_id', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('dob', models.DateField()),
                ('address', models.CharField(max_length=50)),
                ('contact_no', models.PositiveBigIntegerField()),
                ('class_name', models.CharField(max_length=10)),
                ('section_name', models.CharField(max_length=100)),
            ],
        ),
    ]
