# Generated by Django 4.2.5 on 2023-10-04 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('payment_id', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('payment_name', models.CharField(max_length=10)),
            ],
        ),
    ]
