# Generated by Django 4.2.5 on 2023-10-04 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('route_id', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('route_name', models.CharField(max_length=20)),
                ('bus_operator', models.CharField(max_length=20)),
                ('driver_id', models.CharField(max_length=20, unique=True)),
                ('driver_name', models.CharField(max_length=20)),
                ('contact_no', models.BigIntegerField()),
            ],
        ),
    ]
