# Generated by Django 4.2.5 on 2023-10-04 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('dep_id', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('dep_name', models.CharField(max_length=10)),
            ],
        ),
    ]
